### ISSUE TITLE
Clarify if new workspaces can be added to an existing server

### ISSUE THREAD

**Issue by cinnamon-bun** [earthstar-project/earthstar-graphql#1]
When creating a context you supply a list of workspaces.  Is there a way to add new workspaces while the server is already running?

Any answer is ok, just thinking about documentation.

Earthstar servers could run in a variety of modes:
* With an allowlist of workspaces
* With a blocklist of workspaces
* Accepting or rejecting new workspaces on the fly, and maybe only certain people can add new workspaces

Public cloud servers would likely be more locked down, and local personal servers would be more open.

**Comment by sgwilym** [comment]
They can, but the method right now is not obvious: if you sync using a workspace address that is not currently in context, it will create the workspace.

As for which mode to choose: I think I might do a fancy inversion of control thing and make the context able to take a `canAddWorkspace(keypair, workspaceAddress): boolean` function to the context, where you could define any logic you desired for allowing a workspace to be added: just return `true` if you're using embedded, check if the keypair is valid and in the 'allowed to add list', check if the workspace address in in/not in an array...

**Comment by sgwilym** [comment]
This will be addressed in #4!
